# This is a format job. Pre-commit has a first-party GitHub action, so we use
# that: https://github.com/pre-commit/action

name: Format

on:
  workflow_dispatch:
  pull_request:

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.7
    - name: Install system hooks
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt update -qq
        sudo apt install -qq -y lsb-release wget curl gnupg2
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        sudo apt-get update && apt-get upgrade -q -y
        sudo apt install -qq cppcheck ament-cmake-uncrustify
    - uses: pre-commit/action@v2.0.3
      with:
        extra_args: --all-files --hook-stage manual
