name: Ignition ros2 control CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [edifice]
    env:
      IGNITION_VERSION: ${{ matrix.version }}
    container:
      image: osrf/ros:rolling-desktop
    steps:
    - uses: actions/checkout@v2
    - name: Setup colcon workspace
      id: configure
      run: |
        export DEBIAN_FRONTEND=noninteractive
        cd ..
        mkdir -p /home/ros2_ws/src
        cp -r ign_ros2_control /home/ros2_ws/src/
        apt-get update && apt-get upgrade -q -y
        apt-get update && apt-get install -qq -y \
          python3-colcon-ros \
          python3-colcon-common-extensions \
          python3-rosdep \
          build-essential
        cd /home/ros2_ws/src/
        rosdep init
        rosdep update
        rosdep install --from-paths ./ -i -y --rosdistro rolling --ignore-src
    - name: Build project
      id: build
      run: |
        cd /home/ros2_ws/
        . /opt/ros/rolling/local_setup.sh
        colcon build --packages-up-to ign_ros2_control_demos
    - name: Run tests
      id: test
      run: |
        cd /home/ros2_ws/
        . /opt/ros/rolling/local_setup.sh
        colcon test --event-handlers console_direct+ --packages-select ign_ros2_control ign_ros2_control_demos
        colcon test-result
